### ISSUE TITLE
Confused about Stan 0.10.x and SS 3.x

### ISSUE THREAD

**Issue by grantlucas** [symbiote/silverstripe-phpstan#15]
I see in the README, it says to use `3.x` of this repo to get it working with PHPStan `0.10.x` and SS `3.x` but when I look at the `3.0.0` tag, the requirements in Composer are for SS4 and Stan `0.9`. Am I missing something in how to get this working with SS `3.x` and PHPStan 0`.10`?

Any help would be greatly appreciated as it'd be great to get on Stan `0.10`

**Comment by nglasl** [comment]
Hi @grantlucas, thanks for getting in touch. This is a module that we recently adopted, but from what I can see the documentation you're referencing is only a version _**plan**_. I believe the module only supports `0.9`, but the plan was for it to support `0.10` later on. I might tweak the documentation to make that a little clearer.

**Comment by grantlucas** [comment]
@nglasl Great. Thanks for the clarification! We're currently stuck on SS 3 but would love to get up to Stan .10 so we'll be watching with eagerness. If time permits, I might even see if I can get the ball rolling in the 3.x branch in a fork.

**Comment by nglasl** [comment]
I'm not across what's required to make `0.10` happen, but @grantlucas if you could put a PR through that would be awesome.
