### ISSUE TITLE
Update to support phpstan 0.11

### ISSUE THREAD

**Issue by sminnee** [symbiote/silverstripe-phpstan#20]
Features such as https://github.com/phpstan/phpstan/commit/69ef4b1f1f34fce1b2643cac126e962379663211 will be very handy for analysing SilverStripe codebases. However 0.11 has different method signatures.

Presumably this would require a 4.x version of this module?

**Comment by sminnee** [comment]
OK I've added a PR for this. @silbinarywolf, care to take a look?

**Comment by silbinarywolf** [comment]
@sminnee I haven't worked at Symbiote for about a year now and I no longer work with PHP/SilverStripe :)
Have pinged someone else on the PR for you!

**Comment by nglasl** [comment]
Going to close this issue so we can keep pushing forward on the PR.
