### ISSUE TITLE
Ignore "method doesn't exist" in cases where method call is wrapped in hasMethod if-statement

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-phpstan#4]
Related issue: https://github.com/phpstan/phpstan/issues/308

Need to investigate how to ignore these kinds of errors.

**Comment by nglasl** [comment]
@silbinarywolf can you please confirm if this is still an issue? I noticed heaps of commit references above, but they seem unrelated?

**Comment by nglasl** [comment]
Confirmed on https://github.com/symbiote/silverstripe-phpstan/issues/1 and https://github.com/symbiote/silverstripe-phpstan/issues/18.

**Comment by sminnee** [comment]
Fixed in #21
